Workiva/opentelemetry-dart

- pubspec.yaml
When publishing to the pub server, an error prevents the library from being uploaded due to a dependency being referenced in code yet not listed in the pubspec.yaml
Made this change and then published 0.15.0 to the public pub server.
FYI: @Workiva/observability
> O11Y-2352 : added missing dependency

- pubspec.yaml
Unblocking the upgrade of the http dependency to the newest version. This will allow both the newer http version and the current version. In this way, this release will still be consumable inside Workiva while we upgrade other places to http 0.13.0. A subsequent PR can then raise the dependency to require ^0.13.0 and migrate it to null safety.
Changes the http dependency from `^0.12.0` to `>=0.12.0 <0.14.0`
Automated tests in Github Actions
> Update http to ^0.13.0

- pubspec.yaml
Widen the http dependency range on the 0.14.x release line as well so that consumers who are on 0.14.x can resolve to http 0.13.x
Note this merge is targeting the 0.14.x branch, where a 0.14.4 release will be created from.
> O11Y-2363: Widen http on 0.14.x line

- lib/src/api/metrics/noop/noop_meter_provider.dart
- lib/src/experimental_api.dart
- lib/src/experimental_sdk.dart
- lib/src/sdk/common/instrumentation_scope.dart
- lib/src/sdk/metrics/meter.dart
- lib/src/sdk/metrics/meter_provider.dart
- lib/src/sdk/metrics/state/meter_provider_shared_state.dart
- lib/src/sdk/metrics/state/meter_shared_state.dart
- test/unit/sdk/metrics/meter_provider_test.dart
- test/unit/sdk/metrics/state/instrumentation_scope_id_test.dart
It should be possible to associate a Resource with a MeterProvider so that all derivative instruments share the resource.
These changes allow a resource to be passed into the MeterProvider constructor and further build on the effort to bring metrics support to this library
- Please see unit-test
@Workiva/observability
> O11Y-2256 : Resource can be passed into MeterProvider

- .github/workflows/dart_ci.yaml
The CI for this repo depends on the Github token when posting code coverage info to the pull request.  When 3rd parties propose changes, the CI fails because the Github token is not available to those 3rd parties.
Fixes # (issue)
- Disabled codecoverage commenting on the pr (we can revisit later, once we have identified a permanent solution)
The CI on this pr can confirm these changes will not disrupt the CI workflow.
> O11Y-2859: Disable code coverage comments on pull requests

- README.md
The code examples in the README file contain syntax errors. Hence, copy&paste does not provide a functional program.
Fixes # (documentation only)
Fix code examples in README file.
No test, since it is only Documentation change.
> Fix syntax errors in README example code.

- pubspec.yaml
Attempting to package this library with `dart pub publish` results in the following message:
```
Package validation found the following errors:
* line 4, column 1 of lib/src/experimental_api.dart: This package does not have meta in the `dependencies` section of `pubspec.yaml`.
╷
4 │ import 'package:meta/meta.dart';
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
* line 4, column 1 of lib/src/experimental_sdk.dart: This package does not have meta in the `dependencies` section of `pubspec.yaml`.
╷
4 │ import 'package:meta/meta.dart';
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
```
...which prevent this library from releasing.
Fixes # (issue)
`meta` has been added to `pubspec.yaml` at version 1.9.1 (latest).
1. Verified the presence of the described issue without changes to `pubspec.yaml`.
2. Verified the …
> Add dependency for meta to pubspec.yaml

- lib/sdk.dart
- lib/src/api/trace/nonrecording_span.dart
- lib/src/api/trace/span.dart
- lib/src/sdk/platforms/web/trace/web_tracer_provider.dart
- lib/src/sdk/trace/exporters/collector_exporter.dart
- lib/src/sdk/trace/exporters/console_exporter.dart
- lib/src/sdk/trace/exporters/span_exporter.dart
- lib/src/sdk/trace/read_only_span.dart
- lib/src/sdk/trace/read_write_span.dart
- lib/src/sdk/trace/span.dart
- lib/src/sdk/trace/span_processors/batch_processor.dart
- lib/src/sdk/trace/span_processors/simple_processor.dart
- lib/src/sdk/trace/span_processors/span_processor.dart
- lib/src/sdk/trace/tracer.dart
- lib/src/sdk/trace/tracer_provider.dart
- pubspec.yaml
- test/integration/api/propagation/w3c_trace_context_propagator_test.dart
- test/integration/sdk/tracer_test.dart
- test/unit/api/propagation/w3c_trace_context_propagator_test.dart
- test/unit/mocks.dart
- test/unit/sdk/platforms/web/web_trace_provider_test.dart
- test/unit/sdk/span_processors/batch_processor_test.dart
- test/unit/sdk/span_processors/simple_processor_test.dart
- test/unit/sdk/span_test.dart
- test/unit/sdk/trace_provider_test.dart
This PR implements read-only Spans in order to prevent modification during processing and export.
* API:  Added `ReadableSpan`, which contains the read-able portions formerly contained in `Span`.
* API:  `Span` now extends `ReadableSpan` and adds write-able portions.
* SDK:  Added `ReadableSpan` which extends API's `ReadableSpan` to add readable, non-consumer-facing properties like links and attributes.
* SDK:  `Span` now implements API's `Span` and SDK's `ReadableSpan`.
* SDK:  Processors and Exporters now expect `ReadableSpan`s.
* Confirmed passing unit tests
* Updated a test application from a previous version. Confirmed that changes operate properly with no further updates.
> O11Y-1786: Implement Read-Only Spans

- .github/workflows/publish.yaml
GHA "publish" workflow currently contains incorrect regex, which prevents the workflow from triggering properly.  Workflow regex should conform to the following conventions:  https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
This PR updates the tag regex which triggers a publish to pub.dev.
* Pushed an RC tag to my fork containing these changes.
* Confirmed that "publish" workflow started execution.
https://github.com/michaelyeager-wf/opentelemetry-dart/actions/runs/6701443021/job/18208880198
Failure is expected because the referenced reusable workflow does not have access to my fork.
> O11Y-3369: Migrate opentelemetry-dart to GHA

- lib/src/sdk/trace/span_processors/batch_processor.dart
The implementation of Timer for periodic export of spans from BatchSpanProcessor is convoluted and not as null-safe as it should be.  
This PR simplifies how BatchSpanProcessor uses Timer in emitting spans.
* Confirmed that unit tests pass following these changes.
* Loaded these changes in a small testing application and confirmed that it can be used to properly emit traces.
> O11Y-3733: opentelemetry-dart: Implement Improvements to Timer in BatchSpanProcessor

- lib/sdk.dart
Resource is exposed in sdk, but not Attributes for override.
> expose sdk.Attributes

- .github/workflows/publish.yaml
- Dockerfile
This PR updates the GHA publish steps to allow publishing this package to be automated.
> Update GHA publishing steps

- lib/src/sdk/trace/tracer_provider.dart
- test/unit/sdk/trace_provider_test.dart
This mirrors the capability in WebTracerProvider.
I have an opentelemetry implementation using the Dart library (thanks!). I've noticed clock skew between my web/flutter client and dart backend. I have clock synchronisation in the client. This PR allows me to provide my own TimeProvider which exposes synchronised time time, nicely aligning traces between app and server.
The [WebTracerProvider constructor](https://github.com/Workiva/opentelemetry-dart/blob/05f63b64fd813710d78a996a0484cb86ca8bcf98/lib/src/sdk/platforms/web/trace/web_tracer_provider.dart#L25) does allow providing a TimeProvider, but cannot be used in non-web platforms.
Fixes # [99](https://github.com/Workiva/opentelemetry-dart/issues/99) which is expanded in [opentelemetry-js …
> Allow a custom time provider in TracerProviderBase

- lib/src/api/trace/nonrecording_span.dart
- lib/src/api/trace/span.dart
- lib/src/sdk/trace/span.dart
- test/integration/sdk/span_test.dart
Currently it's possible to start spans with a custom `startTime` but it isn't possible to set a custom `endTime` when ending them. This is useful for dispatching spans that happened on a different time window than the moment in which `start()/end()` were called.
This PR adds a new optional `endTime` parameter to the `Span.end()` method which allows a custom `endTime` to be set on the Span rather than always using the `timestamp.now`.
Added a new integration test in which we create a Span with a custom `startTime` and then end it with a custom `endTime` and validate the actual reported timestamps.
> Allow custom timestamps to be used on Span.end()

- lib/src/sdk/platforms/web/time_providers/web_time_provider.dart
- lib/src/sdk/time_providers/datetime_time_provider.dart
- lib/src/sdk/time_providers/time_provider.dart
- lib/web_sdk.dart
- test/unit/sdk/platforms/web/web_time_provider_test.dart
`WebTimeProvider` suffers from rounding issues when using `window.performance.timeOrigin`:
```text
raw (ms) 1722292170313.4
cur (ns) 1722292170313399800
```
The output above comes from the following script:
```dart
// import 'dart:html';
const int _nanosecondsPerMillisecond = 1000 * 1000;
void main() {
final raw = 1722292170313.4;
print('raw (ms) $raw');
final cur = (raw * _nanosecondsPerMillisecond).round();
print('cur (ns) ${cur}');
//   final raw = window.performance.timeOrigin ??
//       window.performance.timing.navigationStart;
//   final cur = (raw * _nanosecondsPerMillisecond).round();
//   print('raw now (ms) ${raw}');
//   print('cur now (ns) ${cur}');
}
```
Update conversion from doubles representing milliseconds to int64s representing nanoseconds.
Additionally, experimental …
> PPI-165 : fix timestamp rounding issues and expose helpers for high res timestamps

- test/unit/sdk/exporters/collector_exporter_test.dart
The wo11y-dart tests refer to the public OTel endpoint. Tests should not use real URLs, but should instead use the `.test` domain, preferably with some arbitrary subdomain.
https://workiva.sourcegraphcloud.com/github.com/Workiva/opentelemetry-dart@9cc09112c1b4ef1f574fe7850f0ef7cdc4f87e96/-/blob/test/unit/sdk/exporters/collector_exporter_test.dart
Unit tests
> O11Y-4831: Use test URL in test

- example/noop_context_manager.dart
- example/w3c_context_propagation.dart
- example/zone_context_manager.dart
- lib/api.dart
- lib/src/experimental_api.dart
`dart analyze` throws a warning when importing experimental libraries due to this [linting rule](https://dart.dev/tools/linter-rules/implementation_imports). This PR moves an experimental API into the public API so that it can be consumed by a production app.
> Make registerGlobalContextManager public API

- example/main.dart
- example/noop_context_manager.dart
- example/w3c_context_propagation.dart
- example/zone_context_manager.dart
- lib/src/api/trace/span_link.dart
- lib/src/sdk/common/limits.dart
- lib/src/sdk/trace/exporters/collector_exporter.dart
- lib/src/sdk/trace/read_only_span.dart
- lib/src/sdk/trace/span.dart
- test/unit/sdk/exporters/collector_exporter_test.dart
- test/unit/sdk/trace/tracer_test.dart
The exporter does not include:
- trace state on the span
- dropped span attributes count
- dropped span links count
- dropped link attributes count
Fixes N/A
The exporter will export:
- trace state on the span
- dropped span attributes count
- dropped span links count
- dropped link attributes count
Pulled changes into a deployed app and spans were successfully exported and retrieved from a trace backend.
> Update trace exporter to include trace state and drop counts

- lib/api.dart
- lib/src/sdk/trace/exporters/collector_exporter.dart
- test/unit/sdk/exporters/collector_exporter_test.dart
When call [client.post](https://github.com/Workiva/opentelemetry-dart/blob/master/lib/src/sdk/trace/exporters/collector_exporter.dart#L54) collector_exporter didn't check if the response is succeeded or not, this PR would like to add retry effort when the response is retryable. 
Please describe the tests that you ran to verify your change. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> O11Y-5250: Add retry

- Makefile
- lib/src/sdk/proto/opentelemetry/proto/collector/logs/v1/logs_service.pb.dart
- lib/src/sdk/proto/opentelemetry/proto/collector/logs/v1/logs_service.pbenum.dart
- lib/src/sdk/proto/opentelemetry/proto/collector/logs/v1/logs_service.pbjson.dart
- lib/src/sdk/proto/opentelemetry/proto/collector/logs/v1/logs_service.pbserver.dart
- lib/src/sdk/proto/opentelemetry/proto/logs/v1/logs.pb.dart
- lib/src/sdk/proto/opentelemetry/proto/logs/v1/logs.pbenum.dart
- lib/src/sdk/proto/opentelemetry/proto/logs/v1/logs.pbjson.dart
- lib/src/sdk/proto/opentelemetry/proto/logs/v1/logs.pbserver.dart
To add proto generated dart files. Next PR will be to create API for log.
Add generated proto files.
Please describe the tests that you ran to verify your change. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
1. Ran unit tests
> feat: proto logs

- lib/src/api/context/context.dart
1. CI fails on my PR https://github.com/Workiva/opentelemetry-dart/pull/203
2. Suspect CI failed due to `warning` output when running `make analyze`
1. Remove unused variable.
1. CI status
> chore: remove unused variable

- lib/src/api/open_telemetry.dart
- test/api/open_telemetry_test.dart
`trace` and `traceSync` have a `newRoot` optional parameter that works by using `Context.root` to start the span. However, if there is a context with a span attached to the root zone, then using `Context.root` will make the span a child of the one held by the context attached to the root zone.
The `Tracer` defined by the SDK supports the `newRoot` optional parameter that results in appropriately configuring the span's parent span context to be invalid regardless of any span potentially visible via the given context.
However, the `Tracer` defined by the API does not support the `newRoot` optional parameter. Ideally, this interface would be updated to include the optional parameter. But this is a breaking change.
Therefore, to resolve the issue of `newRoot` not creating root spans, `trace` …
> Fix trace and traceSync not creating root spans when newRoot is true
